server:
  port: 8080

spring:
  application:
    name: portfolio-analyzer

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# CORS configuration
app:
  cors:
    allowed-origins: http://localhost:5173
